development:
  adapter: postgresql
  encoding: unicode
  database: lt_api_dev
  pool: 5
  username: bazis
  password: test
  host: localhost
  port: 5433


test:
  adapter: postgresql
  encoding: unicode
  database: lt_api_test
  pool: 5
  username: bazis
  password: test
  host: localhost
  port: 5433


production:
  adapter: postgresql
  encoding: unicode
  database: lt_api_prod
  pool: 5
  username: bazis
  password: test
  host: localhost
  port: 5433